steps = [
    {'step': 1, 'positions': [
        {'name': 'Лицом вверх', 'duration_min': 1.5},
        {'name': 'На животе', 'duration_min': 1.5},
        {'name': 'Левый бок', 'duration_min': 1},
        {'name': 'Правый бок', 'duration_min': 1},
        {'name': 'В тени', 'duration_min': 3},
    ]},
    {'step': 2, 'positions': [
        {'name': 'Лицом вверх', 'duration_min': 2},
        {'name': 'На животе', 'duration_min': 2},
        {'name': 'Левый бок', 'duration_min': 1},
        {'name': 'Правый бок', 'duration_min': 1},
        {'name': 'В тени', 'duration_min': 3},
    ]},
    {'step': 3, 'positions': [
        {'name': 'Лицом вверх', 'duration_min': 3},
        {'name': 'На животе', 'duration_min': 3},
        {'name': 'Левый бок', 'duration_min': 1.5},
        {'name': 'Правый бок', 'duration_min': 1.5},
        {'name': 'В тени', 'duration_min': 5},
    ]},
    {'step': 4, 'positions': [
        {'name': 'Лицом вверх', 'duration_min': 5},
        {'name': 'На животе', 'duration_min': 5},
        {'name': 'Левый бок', 'duration_min': 2.5},
        {'name': 'Правый бок', 'duration_min': 2.5},
        {'name': 'В тени', 'duration_min': 5},
    ]},
    {'step': 5, 'positions': [
        {'name': 'Лицом вверх', 'duration_min': 7},
        {'name': 'На животе', 'duration_min': 7},
        {'name': 'Левый бок', 'duration_min': 3},
        {'name': 'Правый бок', 'duration_min': 3},
        {'name': 'В тени', 'duration_min': 7},
    ]},
    {'step': 6, 'positions': [
        {'name': 'Лицом вверх', 'duration_min': 9},
        {'name': 'На животе', 'duration_min': 9},
        {'name': 'Левый бок', 'duration_min': 5},
        {'name': 'Правый бок', 'duration_min': 5},
        {'name': 'В тени', 'duration_min': 10},
    ]},
    {'step': 7, 'positions': [
        {'name': 'Лицом вверх', 'duration_min': 12},
        {'name': 'На животе', 'duration_min': 12},
        {'name': 'Левый бок', 'duration_min': 7},
        {'name': 'Правый бок', 'duration_min': 7},
        {'name': 'В тени', 'duration_min': 10},
    ]},
    {'step': 8, 'positions': [
        {'name': 'Лицом вверх', 'duration_min': 15},
        {'name': 'На животе', 'duration_min': 15},
        {'name': 'Левый бок', 'duration_min': 10},
        {'name': 'Правый бок', 'duration_min': 10},
        {'name': 'В тени', 'duration_min': 10},
    ]},
    {'step': 9, 'positions': [
        {'name': 'Лицом вверх', 'duration_min': 20},
        {'name': 'На животе', 'duration_min': 20},
        {'name': 'Левый бок', 'duration_min': 15},
        {'name': 'Правый бок', 'duration_min': 15},
        {'name': 'В тени', 'duration_min': 15},
    ]},
    {'step': 10, 'positions': [
        {'name': 'Лицом вверх', 'duration_min': 25},
        {'name': 'На животе', 'duration_min': 25},
        {'name': 'Левый бок', 'duration_min': 20},
        {'name': 'Правый бок', 'duration_min': 20},
        {'name': 'В тени', 'duration_min': 20},
    ]},
    {'step': 11, 'positions': [
        {'name': 'Лицом вверх', 'duration_min': 35},
        {'name': 'На животе', 'duration_min': 35},
        {'name': 'Левый бок', 'duration_min': 25},
        {'name': 'Правый бок', 'duration_min': 25},
        {'name': 'В тени', 'duration_min': 30},
    ]},
    {'step': 12, 'positions': [
        {'name': 'Лицом вверх', 'duration_min': 45},
        {'name': 'На животе', 'duration_min': 45},
        {'name': 'Левый бок', 'duration_min': 30},
        {'name': 'Правый бок', 'duration_min': 30},
        {'name': 'В тени', 'duration_min': 40},
    ]},
]
